apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - {key: akuity.io/argo-cd-cluster-name, operator: NotIn, values: [in-cluster]}
          - list:
              elements:
              - env: dev
              - env: uat
              - env: prod
  template:
    metadata:
      name: 'guestbook-simple-{{env}}'
      annotations:
        kargo.akuity.io/authorized-stage: project01:{{env}}
    spec:
      project: test
      source:
        repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
        targetRevision: main
        path: 'app/env/{{env}}'
      destination:
        name: '{{name}}'
        namespace: 'guestbook-simple-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
