apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: project01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
          checkout:
          - branch: main
            path: ./src
          - branch: env/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/base
          images:
          - image: ghcr.io/afzal442/guestbook
            tag: latest
      - uses: kustomize-build
        config:
          path: ./src/app/env/dev
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-simple-dev
            sources:
            - repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
              kustomize:
               images:
               - repoURL: ghcr.io/afzal442/guestbook
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: project01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
          checkout:
          - branch: main
            path: ./src
          - branch: stage/uat
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: ghcr.io/afzal442/guestbook
      - uses: kustomize-build
        config:
          path: ./src/stages/uat
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/uat
      - uses: argocd-update
        config:
          apps:
          - name: kargo-simple-uat
            sources:
            - repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: project01
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
          checkout:
          - branch: main
            path: ./src
          - branch: stage/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: 
      - uses: kustomize-build
        config:
          path: ./src/stages/prod
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/prod
      - uses: argocd-update
        config:
          apps:
          - name: my-argocd-instance
            sources:
            - repoURL: https://github.com/Cloud-Hacks/kargo-quick-temp
              desiredCommitFromStep: commit
