apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: argocd

images:
- name: ghcr.io/afzal442/guestbook
  newName: ghcr.io/afzal442/guestbook
  newTag: v0.0.1
