name: Publish new image
run-name: Publish new image of guestbook binary

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/publish-guestbook.yml'
permissions:
  packages: write
  attestations: write
  contents: write
  id-token: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: afzal442/guestbook

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: afzal442
          password: ${{ secrets.GH_TOKEN }}
      - name: Pick release color
        run: |
          COLORS=("red" "green" "blue" "yellow" "purple" "orange")
          INDEX=$(( $GITHUB_RUN_NUMBER % ${#COLORS[@]} ))
          echo "APP_COLOR=${COLORS[$INDEX]}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            COLOR=${{ env.APP_COLOR }}
          labels: |
            org.opencontainers.image.title="Guestbook"
            org.opencontainers.image.description="Guestbook demo application"
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.run_number }}-${{ env.APP_COLOR }}
            org.opencontainers.image.url=${{ github.repositoryUrl }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
          annotations: |
            index,manifest:org.opencontainers.image.title="Guestbook"
            index,manifest:org.opencontainers.image.description="Guestbook demo application"
            index,manifest:org.opencontainers.image.revision=${{ github.sha }}
            index,manifest:org.opencontainers.image.version=${{ github.run_number }}-${{ env.APP_COLOR }}
            index,manifest:org.opencontainers.image.url=${{ github.repositoryUrl }}
            index,manifest:org.opencontainers.image.source=${{ github.repositoryUrl }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}-${{ env.APP_COLOR }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Tag release in git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ github.run_number }}-${{ env.APP_COLOR }}" -m "Release ${{ github.run_number }}-${{ env.APP_COLOR }}"
          git push origin "${{ github.run_number }}-${{ env.APP_COLOR }}"
  cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          owner: afzal442
          keep-n-tagged: 5
          exclude-tags: '^pr-'
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-untagged: true
          packages: guestbook
